services:

  backend:
    build:
      context: ./backend
    container_name: task-manager-backend
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
    container_name: task-manager-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend